orchestrator:
  max_duration: 300
  consensus_threshold: 0.7
  max_debate_rounds: 2
  status_check_interval: 1.0
  thread_pool_timeout: 5

agents:
- agent_id: 1
  agent_type: openai
  model_config:
    model: gpt-4o
    tools:
    - live_search
    - code_execution
    max_retries: 3
    max_rounds: 15
    temperature: 0.7
    processing_timeout: 60  # Reduced timeout
    stream: false

- agent_id: 2
  agent_type: gemini
  model_config:
    model: gemini-2.5-flash
    tools:
    - live_search
    - code_execution
    max_retries: 3
    max_rounds: 15
    temperature: 0.7
    processing_timeout: 60  # Reduced timeout
    stream: false

streaming_display:
  display_enabled: true
  max_lines: 20
  save_logs: false  # Disable file logging for faster startup

logging:
  log_dir: logs
  non_blocking: true  # Enable non-blocking mode to prevent startup delays 